codes/blog/urls.py
from django.urls import path, re_path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.AllPostView.as_view(), name='blog_all'),
    re_path(r'^detail/(?P<slug>[\w\-\u0600-\u06FF]+)$', views.DetailBlogView.as_view(), name='detail'),
    path('comment/create/<int:blog_id>', views.CreateCommentView.as_view(), name='create_comment'),
    path('comment/reply/create/<int:blog_id>/<int:comment_id>/',
        views.CreateCommentReplyView.as_view(), name='creat_reply_comment'),
    path('favorite/<int:blog_id>/', views.WorkOnFavoriteView.as_view() ,name='favorite'),
    path('like/<int:blog_id>/', views.LikeView.as_view(), name='like'),
]

codes/panel/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'panel'

change_info = [
    path('phone/', views.ChangePhoneUser.as_view(), name='change_phone'),
    path('email/', views.ChangeEmailUser.as_view(), name='change_email'),
    path('info/', views.ChangeBaseInfoView.as_view(), name='change_info'),
]
blog_activity = [
    path('', views.MyBlogView.as_view(), name='my_blog'),
    path('create/', views.CreateBlogView.as_view(), name='create_blog'),
    path('detail/<int:blog_id>', views.DetailBlogView.as_view(), name='detail_blog'),
    path('delete/<int:blog_id>', views.DeleteBlogView.as_view(), name='delete_blog'),
    path('update/<int:blog_id>', views.UpdateBlogView.as_view(), name='update_blog'),
]
favorite = [
    path('', views.MyFavoriteBlogView.as_view(), name='favorite')
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_panel'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('verify/phone/', views.VerifyPhoneView.as_view(), name='verify_phone'),
    path('change/', include(change_info)),
    path('blog/', include(blog_activity)),
    path('favorite/', include(favorite)),
]

codes/weblog/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls', namespace='panel')),
    path('', include('blog.urls', namespace='blog')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.LANGUAGE_CODE == 'fa':
    admin.site.site_header = 'مدیریت پروژه'
    admin.site.site_title = 'پنل مدیریت'
    admin.site.index_title = 'به پنل مدیریت خوش آمدید'

codes/panel/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.db import models

# import from panel app
from .managers import UserManagerConfig

# import from extra modules
from extra_module.utils import username_validation, phone_validataion

# third party library
from datetime import timedelta

class User(PermissionsMixin, AbstractBaseUser):
    username = models.CharField(_('نام کاربری'), max_length=60, validators=[username_validation],
        unique=True, blank=True, null=True
    )
    phone = models.CharField(_("شماره همراه"), max_length=11, unique=True, validators=[phone_validataion])
    email = models.EmailField(_("آدرس اینترنتی"), max_length=60, unique=True, blank=True, null=True)

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    # verify phone or email is boolean
    phone_verified = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['username', 'email']

    objects = UserManagerConfig()

    @property
    def is_staff(self):
        return self.is_admin
    
    def get(self, key, default=None):
        return self.data.get(key, default)
    

    class Meta:
        verbose_name = 'کاربر'
        verbose_name_plural = 'کاربران'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile = models.ImageField(_("پروفایل"), upload_to='user',
        blank=True, null=True, default='user_default_profile.png')
    bio = models.TextField(_('توضیحات'), max_length=120, blank=True, null=True)
    first_name = models.CharField(_('نام'), max_length=30, blank=True, null=True)
    last_name = models.CharField(_('نام خانوادگی'), max_length=30, blank=True, null=True)

        
    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    
    @property
    def user_info(self):
        if self.first_name and self.last_name:
            return self.full_name
        else:
            return self.user.username


class OTP(models.Model):
    phone = models.CharField(_("شماره همراه"), max_length=11, unique=True)
    code = models.CharField(_("کد تایید"), max_length=6)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.phone
    
    def is_alive(self):
        '''check expiration date'''
        return self.created+timedelta(minutes=3) > timezone.now()

    class Meta:
        verbose_name = 'رمز یک بار مصرف'
        verbose_name_plural = 'رمزهای یک بار مصرف'

codes/panel/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.core.paginator import Paginator
from django.contrib import messages
from django.views import View

# import from blog app
from blog.models import Blog

# import from panel app
from .forms import (
    LoginUserForm, RegisterUserForm, ChangeBaseInfoForm,
    VerifyPhoneForm, ChangeEmailForm, ChangePhoneForm,
    PostBlogForm
)
from .models import User, OTP
from .mixins import (
    MyLoginRequiredMixin, AnonymousRequiredMixin, SendBlogPermissionMixin,
    OwnerBlogMixin
)

# import form module
from extra_module.utils import send_verify_phone

# import third module
from random import randint


class RegisterUserView(AnonymousRequiredMixin, View):
    template_name = 'panel/register.html'
    form_class = RegisterUserForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            # generate verify code
            code = randint(100000, 999999)

            # save user info in session
            request.session['user_registration_info'] = {
                'phone':cd['phone'],
                'password':cd['password1']
            }

            # send verify code to user phone
            send_verify_phone(cd['phone'], code)

            # save code in otp model
            OTP.objects.update_or_create(
                phone=cd['phone'],
                defaults={'code': code}
            )

            messages.success(request, 'با موفقیت برای شماره همراه شما کد تایید ارسال شد')
            return redirect('panel:verify_phone')           
        messages.error(request, 'Please correct the errors below')
        return render(request, self.template_name, {'form':form})


class LoginUserView(AnonymousRequiredMixin, View):
    template_name = 'panel/login.html'
    form_class = LoginUserForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            cd = form.cleaned_data

            user = authenticate(request, phone=cd['info'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'login successfully')

                next = request.GET.get('next', None)
                return redirect(next if next else 'panel:home_panel')
            else:
                messages.error(request, "your input info was wrong")

        return render(request, self.template_name, {'form':form})
    

class LogoutUserView(MyLoginRequiredMixin, View):
    def get(self, request):
        #TODO: The address of this method will be determined later.
        logout(request)
        messages.success(request, 'logout successfully')
        return redirect('blog:blog_all')


class HomeView(MyLoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'panel/home.html')
    

class VerifyPhoneView(AnonymousRequiredMixin, View):
    form_class = VerifyPhoneForm
    template_name = 'panel/verify_phone.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user_code = form.cleaned_data['code']
            self.info = request.session['user_registration_info']

            try:
                found_otp_code = OTP.objects.get(code=user_code, phone=self.info['phone'])

                if found_otp_code.is_alive():
                    # create user: user info in session object
                    user = User.objects.create(
                        phone = self.info['phone'],
                        password = self.info['password'],
                        phone_verified = True
                    )

                    # login registered user
                    login(request, user, backend='django.contrib.auth.backends.ModelBackend')

                    self.clear_data(found_otp_code)
                    
                    messages.success(request, 'your accounts was successfully created')
                    return redirect('panel:home_panel')
                
                messages.error(request, 'code was expired')
                self.clear_data(found_otp_code)

            except OTP.DoesNotExist:
                messages.error(request, 'input code was wrong')
        return render(request, self.template_name, {'form':form})
    

    def clear_data(self, otp):
        '''create session and delete otp code'''
        # clear session
        del self.info
        # delete otp code
        otp.delete()


class ChangePhoneUser(MyLoginRequiredMixin, View):
    template_name = 'panel/change_phone.html'
    form_class = ChangePhoneForm

    def get(self, request):
        form = self.form_class(instance=request.user)
        return render(request, self.template_name, {'form':form})
    
    
    def post(self, request):
        form = self.form_class(request.POST, instance=request.user)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'your phone succeesfully change')
            return redirect('panel:home_panel')
        messages.error(request, 'Please correct the errors below')
        return render(request, self.template_name, {'form':form})
    

class ChangeEmailUser(MyLoginRequiredMixin, View):
    template_name = 'panel/change_email.html'
    form_class = ChangeEmailForm

    def get(self, request):
        form = self.form_class(instance=request.user)
        return render(request, self.template_name, {'form':form})
    

    def post(self, request):
        form = self.form_class(request.POST, instance=request.user)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'your email succeesfully change')
            return redirect('panel:home_panel')
        messages.error(request, 'Please correct the errors below')
        return render(request, self.template_name, {'form':form})
    

class ChangeBaseInfoView(MyLoginRequiredMixin, View):
    template_name = 'panel/change_info.html'
    form_class = ChangeBaseInfoForm

    def get(self, request):
        form = self.form_class(instance=request.user.profile, initial={'username':request.user.username})
        return render(request, self.template_name, {'form':form})
    
    
    def post(self, request):
        form = self.form_class(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save(form.cleaned_data)
            messages.success(request, 'your info save successfully')
            return redirect('panel:home_panel')
        messages.error(request, 'Please correct the errors below')
        return render(request, self.template_name, {'form':form})


class CreateBlogView(MyLoginRequiredMixin, SendBlogPermissionMixin, View):
    from_class = PostBlogForm
    template_name = 'blog/create_blog.html'

    def get(self, request):
        form = self.from_class()
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        form = self.from_class(request.POST, request.FILES)
        if form.is_valid():
            blog = form.save(request, form.cleaned_data)
            messages.success(request, 'your blog create successfully')
            return redirect(blog.get_panel_detail_blog_url())

        messages.error(request, 'Please correct the errors below')
        return render(request, self.template_name, {'form':form})
    

class MyBlogView(MyLoginRequiredMixin, View):
    template_name = 'blog/blog_list.html'
    
    def get(self, request):
        page = request.GET.get('page', 1)

        blogs = request.user.blogs.filter(is_active=True)
        paginate = Paginator(blogs, per_page=10)
        blogs = paginate.get_page(page)

        return render(request, self.template_name, {'blogs':blogs})
    

class DetailBlogView(MyLoginRequiredMixin, OwnerBlogMixin, View):
    template_name = 'blog/detail_blog.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'blog':self.blog})
    

class DeleteBlogView(MyLoginRequiredMixin, OwnerBlogMixin, View):
    def get(self, request, *args, **kwargs):
        self.blog.is_active = False
        self.blog.save()
        messages.success(request, 'successfully delete blog')
        return redirect('panel:my_blog')


class UpdateBlogView(MyLoginRequiredMixin, OwnerBlogMixin, View):
    form_class = PostBlogForm
    template_name = 'blog/update_blog.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(instance=self.blog)
        return render(request, self.template_name, {'form':form})
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES, instance=self.blog)
        
        if form.is_valid():
            form.save(request, form.cleaned_data, update=True)
            messages.success(request, 'your blog updated successfully')
            return redirect(self.blog.get_panel_detail_blog_url())
 
        messages.error(request, 'Please correct the errors below')
        return render(request, self.template_name, {'form':form})
    

class MyFavoriteBlogView(MyLoginRequiredMixin, View):
    template_name = 'blog/listing_favorite.html'

    def get(self, request):
        favorites = request.user.favorites.filter(blog__is_active=True)
        return render(request, self.template_name, {'favorites':favorites})

codes/panel/templates/panel/blog_list.html
{% extends 'base.html' %}

{% block title %} My Blog Listing Page {% endblock %}

{% block body %}
<h1 class="text-center mb-5">My Blog</h1>
{% if blogs %}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Published</th>
            <th scope="col">Activity</th>
        </tr>
    </thead>
    <tbody>
        {% for blog in blogs %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{blog.title}}</td>
            <td>
                <img style="width: 25px;" src="/static/admin/img/icon-{% if blog.is_active %}yes{% else %}no{% endif %}.svg" alt="">
            </td>
            <td>
                <a href="" class="btn btn-danger">remove</a>
                <a href="" class="btn btn-info">update</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include 'include/blog_paginator.html' %}
{% else %}
<p class="alert alert-danger">you have no blog</p>
{% endif %}
{% endblock %}

codes/panel/templates/panel/change_email.html
{% extends 'base.html' %}

{% block title %} Change Email Page {% endblock %}

{% block body %}
<div class="mx-auto card mx-auto col-md-6" style="padding: 0px;">
    <div class="card-header">Change Email</div>
    <form class="card-body" action="" method="post">
        {% for field in form %}
            <div class="fieldWrapper">
                <div class="label_and_error">
                    <div class="label_form_side">
                        {{ field.label_tag }}
                    </div>
                    {{ field.errors }}
                </div>
                <div>{{ field }}</div>
            </div>
        {% endfor %}
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            <input type="submit" value="Change Email" class="btn btn-primary btn-lg mt-3">
        </div>
    </form>
</div>
{% endblock %}
{% block footer %}{% endblock %}

codes/panel/templates/panel/change_info.html
{% extends 'base.html' %}

{% block title %} Change Info Page {% endblock %}

{% block body %}
<div class="mx-auto card mx-auto" style="padding: 0px;">
    <div class="card-header">Change Info</div>
    <form class="card-body d-flex justify-content-center align-items-center" style="flex-wrap: wrap;" action="" method="post" enctype="multipart/form-data">
        {% if form.instance.profile %}
        <div class="image-container mx-auto">
            <img style="margin: 0px auto;" src="{{ form.instance.profile.url }}" alt="Profile Picture">
        </div>
        {% endif %}
        {% for field in form %}
        <div class="fieldWrapper col-md-6">
            <div class="label_and_error">
                <div class="label_form_side">
                    {{ field.label_tag }}
                </div>
                {{ field.errors }}
            </div>
            <div>{{ field }}</div>
        </div>
        {% endfor %}
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            <input type="submit" value="Change" class="btn btn-primary btn-lg mt-3">
        </div>
    </form>
</div>
{% endblock %}
{% block footer %}{% endblock %}

codes/panel/templates/panel/change_phone.html
{% extends 'base.html' %}

{% block title %} Change Phone Page {% endblock %}

{% block body %}
<div class="mx-auto card mx-auto col-md-6" style="padding: 0px;">
    <div class="card-header">Change Phone</div>
    <form class="card-body" action="" method="post">
        {% for field in form %}
            <div class="fieldWrapper">
                <div class="label_and_error">
                    <div class="label_form_side">
                        {{ field.label_tag }}
                    </div>
                    {{ field.errors }}
                </div>
                <div>{{ field }}</div>
            </div>
        {% endfor %}
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            <input type="submit" value="Change Phone" class="btn btn-primary btn-lg mt-3">
        </div>
    </form>
</div>
{% endblock %}
{% block footer %}{% endblock %}

codes/panel/templates/panel/home.html
{% extends 'base.html' %}
{% load my_filter %}
{% block title %} Panel Page {% endblock %}

{% block body %}
<div>
    <div style="text-align: center;" class="mb-5">
        <h1>Welcome back {{request.user.profile.user_info|default:request.user.phone}}</h1>
    </div>
    <div class="profile-container">
        <div class="image-container col-xl-3">
            <img src="{{request.user.profile.profile.url}}" alt="user profile image">
        </div>
        <div class="col-xl-8 d-flex justify-content-between align-items-center flex-wrap">
            <div class="col-md-6">
                <p>Email validity status
                    {% if request.user.email_verified %}
                    <svg style="color: green" width="25px" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M9 12.75 11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043A3.745 3.745 0 0 1 12 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 0 1-3.296-1.043 3.745 3.745 0 0 1-1.043-3.296A3.745 3.745 0 0 1 3 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 0 1 1.043-3.296 3.746 3.746 0 0 1 3.296-1.043A3.746 3.746 0 0 1 12 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.296A3.745 3.745 0 0 1 21 12Z" />
                    </svg>
                    {% else %}
                    <svg style="color:red" width="25px" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                    </svg>
                    {% endif %}
                </p>
                <p>Phone validity status
                    {% if request.user.phone_verified %}
                    <svg style="color: green" width="25px" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M9 12.75 11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043A3.745 3.745 0 0 1 12 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 0 1-3.296-1.043 3.745 3.745 0 0 1-1.043-3.296A3.745 3.745 0 0 1 3 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 0 1 1.043-3.296 3.746 3.746 0 0 1 3.296-1.043A3.746 3.746 0 0 1 12 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.296A3.745 3.745 0 0 1 21 12Z" />
                    </svg>
                    {% else %}
                    <svg style="color:red" width="25px" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                    </svg>
                    {% endif %}
                </p>
                <p>First name: {{request.user.profile.first_name|set_default}}</p>
                <p>Last name: {{request.user.profile.last_name|set_default}}</p>
            </div>
            <div class="col-md-6">
                <p>Email: {{request.user.email|set_default}}</p>
                <p>Phone: {{request.user.phone}}</p>
                <p>Username: {{request.user.username|set_default}}</p>
            </div>
        </div>
    </div>
    <div class="my-3 d-flex f-wrap justify-content-between align-items-center flex-wrap">
        <div>
            <a href="{% url 'panel:change_info' %}" class="btn btn-primary">Change Base Info</a>
            <a href="{% url 'panel:change_phone' %}" class="btn btn-primary">Change Phone</a>
            <a href="{% url 'panel:change_email' %}" class="btn btn-primary">Change Email</a>
            <a href="" class="btn btn-primary">Verify Phone</a>
            <a href="" class="btn btn-primary">Verify Email</a>
        </div>
        <div>
            <a href="{% url 'panel:favorite' %}" class="btn btn-success">Favorite</a>
            <a href="{% url 'panel:create_blog' %}" class="btn btn-success">Create Blog</a>
            <a href="{% url 'panel:my_blog' %}" class="btn btn-success">My Blog</a>
        </div>
    </div>
    <hr class="roler">
    <p>Description: {{request.user.profile.bio|set_default}}</p>
</div>
{% endblock %}

codes/panel/templates/panel/login.html
{% extends 'base.html' %}

{% block title %} Login Page {% endblock %}

{% block body %}
  
<div class="mx-auto card mx-auto col-md-6" style="padding: 0px;">
    <div class="card-header">Login Form</div>
    <form class="card-body" action="" method="post">
        {% for field in form %}
            <div class="fieldWrapper">
                <div class="label_and_error">
                    <div class="label_form_side">
                        {{ field.label_tag }}
                    </div>
                    {{ field.errors }}
                </div>
                <div>{{ field }}</div>
            </div>
        {% endfor %}
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            <input type="submit" value="Login" class="btn btn-primary btn-lg mt-3">
        </div>
        <a class="d-block" href="{% url 'panel:register' %}">Register</a>
        <a class="d-block" href="">Forget Password</a>
    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}

codes/panel/templates/panel/post_blog.html
{% extends 'base.html' %}

{% block title %} Post Blog Page {% endblock %}

{% block body %}

<div class="mx-auto card mx-auto" style="padding: 0px;">
    <div class="card-header">Post Blog</div>
    <form class="card-body needs-validation d-flex flex-wrap justify-content-center" action="" method="post" enctype="multipart/form-data">
        {% for field in form %}
            <div class="fieldWrapper col-md-6">
                <div class="label_and_error">
                    <div class="label_form_side">
                        {{ field.label_tag }}
                    </div>
                    {{ field.errors }}
                </div>
                <div>{{ field }}</div>  
            </div>
        {% endfor %}
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            <input type="submit" value="Post" class="btn btn-primary btn-lg mt-3">
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}

codes/panel/templates/panel/register.html
{% extends 'base.html' %}

{% block title %} Register Page {% endblock %}

{% block body %}

<div class="mx-auto card mx-auto col-md-6 " style="padding: 0px;">
    <div class="card-header">Register Form</div>
    <form class="card-body needs-validation" action="" method="post">
        {% for field in form %}
            <div class="fieldWrapper">
                <div class="label_and_error">
                    <div class="label_form_side">
                        {{ field.label_tag }}
                    </div>
                    {{ field.errors }}
                </div>
                <div>{{ field }}</div>
            </div>
        {% endfor %}
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            <input type="submit" value="Register" class="btn btn-primary btn-lg mt-3">
        </div>
        <a class="d-block" href="{% url 'panel:login' %}">i alredy have an account</a>
    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}

codes/panel/templates/panel/verify_phone.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %} Login Page {% endblock %}

{% block body %}
  
<div class="mx-auto card mx-auto col-md-6" style="padding: 0px;">
    <div class="card-header">Verify Code</div>
    <form class="card-body" action="" method="post" novalidate>
        {% for field in form %}
            <div class="fieldWrapper">
                <div class="label_and_error">
                    <div class="label_form_side">
                        {{ field.label_tag }}
                    </div>
                    {{ field.errors }}
                </div>
                <div>{{ field }}</div>
            </div>
        {% endfor %}
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            <input type="submit" value="verify" class="btn btn-primary btn-lg mt-3">
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}