codes/blog/urls.py
from django.urls import path, re_path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.AllPostView.as_view(), name='blog_all'),
    re_path(r'^detail/(?P<slug>[\w\-\u0600-\u06FF]+)$', views.DetailBlogView.as_view(), name='detail'),
    path('comment/create/<int:blog_id>', views.CreateCommentView.as_view(), name='create_comment'),
    path('comment/reply/create/<int:blog_id>/<int:comment_id>/',
        views.CreateCommentReplyView.as_view(), name='creat_reply_comment'),
    path('favorite/<int:blog_id>/', views.WorkOnFavoriteView.as_view() ,name='favorite'),
    path('like/<int:blog_id>/', views.LikeView.as_view(), name='like'),
]

codes/panel/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'panel'

change_info = [
    path('phone/', views.ChangePhoneUser.as_view(), name='change_phone'),
    path('email/', views.ChangeEmailUser.as_view(), name='change_email'),
    path('info/', views.ChangeBaseInfoView.as_view(), name='change_info'),
]
blog_activity = [
    path('', views.MyBlogView.as_view(), name='my_blog'),
    path('create/', views.CreateBlogView.as_view(), name='create_blog'),
    path('detail/<int:blog_id>', views.DetailBlogView.as_view(), name='detail_blog'),
    path('delete/<int:blog_id>', views.DeleteBlogView.as_view(), name='delete_blog'),
    path('update/<int:blog_id>', views.UpdateBlogView.as_view(), name='update_blog'),
]
favorite = [
    path('', views.MyFavoriteBlogView.as_view(), name='favorite')
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_panel'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('verify/phone/', views.VerifyPhoneView.as_view(), name='verify_phone'),
    path('change/', include(change_info)),
    path('blog/', include(blog_activity)),
    path('favorite/', include(favorite)),
]

codes/weblog/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls', namespace='panel')),
    path('', include('blog.urls', namespace='blog')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.LANGUAGE_CODE == 'fa':
    admin.site.site_header = 'مدیریت پروژه'
    admin.site.site_title = 'پنل مدیریت'
    admin.site.index_title = 'به پنل مدیریت خوش آمدید'

codes/templates/include/blog_paginator.html
<div class="tm-mt-40 tm-mb-40">
    <div class="new_paginator">
        <a href="{% if blogs.has_previous %}?page={{ blogs.previous_page_number }}{% endif %}" 
            class="mb-2 tm-btn tm-btn-primary tm-prev-next {% if not blogs.has_previous %}disabled{% endif %}">
                Prev
        </a>
        <nav class="tm-paging-nav d-inline-block">
            <ul>
                {% for num in blogs.paginator.page_range %}
                {% if blogs.number == num %}
                <li class="tm-paging-item active">
                    <span class="mb-2 tm-btn tm-paging-link">{{ num }}</span>
                </li>
                {% else %}
                <li class="tm-paging-item">
                    <a href="?page={{ num }}" class="mb-2 tm-btn tm-paging-link">{{ num }}</a>
                </li>
                {% endif %}
            {% endfor %}
            </ul>
        </nav>
        <a href="{% if blogs.has_next %}?page={{ blogs.next_page_number }}{% endif %}" 
        class="mb-2 tm-btn tm-btn-primary tm-prev-next {% if not blogs.has_next %}disabled{% endif %}">
                Next
        </a>
    </div>                
</div>

codes/templates/include/header.html
<header class="tm-header" id="tm-header">
    <div class="tm-header-wrapper">
        <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="tm-site-header">
            <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-times fa-2x"></i></div>
            <h1 style="font-size: 30px !important;" class="text-center">Weblog Project</h1>
        </div>
        <nav class="tm-nav" id="tm-nav">
            <ul>
                <li class="tm-nav-item {% if request.resolver_match.url_name == 'home_panel' %}active{% endif %}"><a href="{% url 'panel:home_panel' %}" class="tm-nav-link">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        panel
                    </a></li>
                {% if request.user.is_authenticated %}
                <li class="tm-nav-item"><a href="{% url 'panel:logout' %}" class="tm-nav-link">
                        <i class="fa fa-sign-out" aria-hidden="true"></i>
                        logout
                    </a></li>
                {% else %}
                <li class="tm-nav-item {% if request.resolver_match.url_name == 'login' or request.resolver_match.url_name == 'register' %}active{% endif %}"><a href="{% url 'panel:login' %}" class="tm-nav-link">
                    <i class="fa fa-sign-in" aria-hidden="true"></i>
                        Login or Register
                    </a></li>
                {% endif %}
                <li class="tm-nav-item {% if request.resolver_match.url_name == 'blog_all' %}active{% endif %}"><a href="{% url 'blog:blog_all' %}" class="tm-nav-link">
                        <i class="fas fa-home"></i>
                        Blog Home
                    </a></li>
                <li class="tm-nav-item "><a href="about.html" class="tm-nav-link">
                        <i class="fas fa-users"></i>
                        About Xtra
                    </a></li>
                <li class="tm-nav-item"><a href="contact.html" class="tm-nav-link">
                        <i class="far fa-comments"></i>
                        Contact Us
                    </a></li>
            </ul>
        </nav>
        <div class="tm-mb-65">
            <a rel="nofollow" href="https://fb.com/templatemo" class="tm-social-link">
                <i class="fab fa-facebook tm-social-icon"></i>
            </a>
            <a href="https://twitter.com" class="tm-social-link">
                <i class="fab fa-twitter tm-social-icon"></i>
            </a>
            <a href="https://instagram.com" class="tm-social-link">
                <i class="fab fa-instagram tm-social-icon"></i>
            </a>
            <a href="https://linkedin.com" class="tm-social-link">
                <i class="fab fa-linkedin tm-social-icon"></i>
            </a>
        </div>
        <p class="tm-mb-80 pr-5 text-white">
            Xtra Blog is a multi-purpose HTML template from TemplateMo website. Left side is a sticky menu bar. Right
            side content will scroll up and down.
        </p>
    </div>
</header>

codes/templates/include/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{msg|safe}}</p>
    {% endfor %}
{% endif %}