codes/blog/urls.py
from django.urls import path, re_path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.AllPostView.as_view(), name='blog_all'),
    re_path(r'^detail/(?P<slug>[\w\-\u0600-\u06FF]+)$', views.DetailBlogView.as_view(), name='detail'),
    path('comment/create/<int:blog_id>', views.CreateCommentView.as_view(), name='create_comment'),
    path('comment/reply/create/<int:blog_id>/<int:comment_id>/',
        views.CreateCommentReplyView.as_view(), name='creat_reply_comment'),
    path('favorite/<int:blog_id>/', views.WorkOnFavoriteView.as_view() ,name='favorite'),
    path('like/<int:blog_id>/', views.LikeView.as_view(), name='like'),
]

codes/panel/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'panel'

change_info = [
    path('phone/', views.ChangePhoneUser.as_view(), name='change_phone'),
    path('email/', views.ChangeEmailUser.as_view(), name='change_email'),
    path('info/', views.ChangeBaseInfoView.as_view(), name='change_info'),
]
blog_activity = [
    path('', views.MyBlogView.as_view(), name='my_blog'),
    path('create/', views.CreateBlogView.as_view(), name='create_blog'),
    path('detail/<int:blog_id>', views.DetailBlogView.as_view(), name='detail_blog'),
    path('delete/<int:blog_id>', views.DeleteBlogView.as_view(), name='delete_blog'),
    path('update/<int:blog_id>', views.UpdateBlogView.as_view(), name='update_blog'),
]
favorite = [
    path('', views.MyFavoriteBlogView.as_view(), name='favorite')
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_panel'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('verify/phone/', views.VerifyPhoneView.as_view(), name='verify_phone'),
    path('change/', include(change_info)),
    path('blog/', include(blog_activity)),
    path('favorite/', include(favorite)),
]

codes/weblog/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls', namespace='panel')),
    path('', include('blog.urls', namespace='blog')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.LANGUAGE_CODE == 'fa':
    admin.site.site_header = 'مدیریت پروژه'
    admin.site.site_title = 'پنل مدیریت'
    admin.site.index_title = 'به پنل مدیریت خوش آمدید'

codes/blog/models.py
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.urls import reverse
from django.db import models

# thir party importing
from django_ckeditor_5.fields import CKEditor5Field

from .managers import ActiveManager, FristCommentManager

class BaseModle(models.Model):
    title = models.CharField(_("عنوان"), max_length=120, unique=True)
    slug = models.SlugField(max_length=120, unique=True, allow_unicode=True)

    def __str__(self):
        return self.title[:30]


    class Meta:
        abstract = True


class Category(BaseModle):
    sub = models.ForeignKey(
        'self', verbose_name=_('زیر مجموعه دسته بندی'),  on_delete=models.CASCADE,
        related_name='sub_category', blank=True, null=True
    )
    is_sub = models.BooleanField(_('وضعیت زیر مجموعه بودن'), default=False)

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'


class Blog(BaseModle):
    baner = models.ImageField(_('بنر'), upload_to='blog')
    text = CKEditor5Field(_('متن'))
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_('نویسنده'),  on_delete=models.CASCADE, related_name='blogs'
    )
    cates = models.ManyToManyField(Category, verbose_name=_("دسته بندی"), related_name='blogs')
    is_active = models.BooleanField(_('وضعیت انتشار'), default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, verbose_name=_('تاریخ'))
    
    objects = models.Manager()
    config = ActiveManager()

    def can_add_to_favorite(self, request):
        '''check user can add to favorite or no'''
        if not request.user.is_authenticated:
            return True
        return not self.favorites.filter(blog=self, user=request.user).exists()

    def can_like(self, request):
        '''check user can like blog or no'''
        if not request.user.is_authenticated:
            return True
        return not self.blog_like.filter(user=request.user).exists()
    
    def like_count(self):
        '''count all like for especial blog'''
        return self.blog_like.count()
    
    def comments_count(self):
        '''count all comments for especial blog'''
        return self.comments.filter(is_active=True).count()

    def related_blog(self):
        '''find related blog. just look at categories'''
        return Blog.config.filter(cates__in=self.cates.all()).exclude(id=self.id).distinct()[:5]
    
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug':self.slug})
    
    def get_panel_detail_blog_url(self):
        return reverse('panel:detail_blog', kwargs={'blog_id':self.id})


    class Meta:
        ordering = ('-is_active', '-updated')
        verbose_name = 'بلاگ'
        verbose_name_plural = 'بلاگ ها'

class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('کاربر'),  on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name=_('بلاگ'), related_name='blog_like')

    def __str__(self):
        return f'user {self.user} like blog {self.blog}'
    

    class Meta:
        verbose_name = 'لایک'
        verbose_name_plural = 'لایک ها'


class Follow(models.Model):
    follower = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_('دنبال کننده'),
        on_delete=models.CASCADE, related_name='followers'
    )
    following = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_('دنبال شونده'),
        on_delete=models.CASCADE, related_name='followings'
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('تاریخ'))
    
    def __str__(self):
        return f'user {self.follower.phone} follow {self.following.phone}'


class Comment(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_('کاربر'), on_delete=models.CASCADE, related_name='comments'
    )
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, verbose_name=_('بلاگ'), related_name='comments'
    )
    reply = models.ForeignKey('self', on_delete=models.CASCADE, verbose_name=_('در پاسخ به'),
        related_name='rcomments',  blank=True, null=True
    )
    is_reply = models.BooleanField(_('وضعیت پاسخ'), default=False)
    text = CKEditor5Field(_('متن کامنت'), max_length=250, config_name='simple')
    is_active = models.BooleanField(_('وضعیت انتشار'), default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('تاریخ'))

    objects = models.Manager()
    config = FristCommentManager()

    def __str__(self):
        return self.text[:30]
    

    def reply_comments(self):
        return self.rcomments.filter(is_active=True)


    class Meta:
        ordering = ('-created',)
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها'

    
class Favorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='favorites')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='favorites')

    def __str__(self):
        return f'{self.user} - {self.blog}'
    

    class Meta:
        verbose_name = 'علاقه مندی'
        verbose_name_plural = 'علاقه مندی ها'

codes/blog/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget


class CreateCommentForm(forms.Form):
    text = forms.CharField(
        widget=CKEditor5Widget(
            attrs={'class':"form-control tm-color-secondary col-12 django_ckeditor_5", 'rows':10},
            config_name='simple'
        )
    )

codes/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from django.views import View

# import from blog app
from .models import Blog, Category, Comment, Favorite, Like
from .forms import CreateCommentForm


class AllPostView(View):
    template_name = 'blog/show_all.html'
    
    def get(self, request):
        page = request.GET.get('page', 1)
        search = request.GET.get('q', None)
        category = request.GET.get('category', None)
        blogs = Blog.config.all()
        
        if search:
            blogs = blogs.filter(
                Q(title__contains=search)|
                Q(text__contains=search)
            )

        if category:
            find_category_by_cat = Category.objects.filter(slug=category)
            blogs = blogs.filter(
                cates__in=find_category_by_cat
            )
            category = find_category_by_cat[0].title if find_category_by_cat else None
        
        paginate = Paginator(blogs, per_page=6)
        blogs = paginate.get_page(page)
        
        data = {
            'blogs': blogs,
            'search': search,
            'category': category,
            'result_count': paginate.count,
        }
        return render(request, self.template_name, data)
    

class DetailBlogView(View):
    form_class = CreateCommentForm

    def get(self, request, slug):
        form = self.form_class()
        blog = get_object_or_404(Blog, slug=slug, is_active=True)
        categories = Category.objects.all()
        comments = Comment.config.filter(blog=blog)

        context = {
            'blog':blog,
            'categories':categories,
            'comments':comments,
            'form':form,
            'can_like': blog.can_like(request),
            'can_add_to_favorite': blog.can_add_to_favorite(request)
        }
        return render(request, 'blog/detail.html', context=context)
    

class CreateCommentView(LoginRequiredMixin, View):
    def post(self, request, blog_id):
        form = CreateCommentForm(request.POST)

        if form.is_valid():
            blog = get_object_or_404(Blog, pk=blog_id)
            
            Comment.objects.create(
                user = request.user,
                blog = blog,
                text = form.cleaned_data['text'],
            )
            messages.success(request, 'comment send successfully after check it will be show in the template')
        else:
            messages.error(request, 'something went wrong')
        return redirect('blog:detail', slug=blog.slug)
    

class CreateCommentReplyView(LoginRequiredMixin, View):
    def post(self, request, blog_id, comment_id):
        form = CreateCommentForm(request.POST)

        if form.is_valid():
            blog = get_object_or_404(Blog, pk=blog_id)
            comment = get_object_or_404(Comment, pk=comment_id)

            Comment.objects.craete(
                user=request.user,
                blog=blog,
                reply=comment,
                is_reply=True,
                text=form.cleaned_data['text']
            )
            messages.success(request, 'your comment create successfully. after admin check it will show')
        else:
            messages.error(request, 'something went happen')
        return redirect('blog:detail', slug=blog.slug)


class WorkOnFavoriteView(LoginRequiredMixin, View):
    def get(self, request, blog_id):
        blog = get_object_or_404(Blog, pk=blog_id, is_active=True)

        fav, created = Favorite.objects.get_or_create(
            user=request.user, blog=blog
        )

        if not created:
            fav.delete()

        previous_url = request.META.get('HTTP_REFERER', None)
        return redirect(previous_url if previous_url else reverse('blog:detail', kwargs={'slug':blog.slug}))


class LikeView(LoginRequiredMixin, View):
    def get(self, request, blog_id):
        blog = get_object_or_404(Blog, pk=blog_id)

        like, created = Like.objects.get_or_create(
            blog=blog, user=request.user
        )
        
        if not created:
            like.delete()

        return redirect('blog:detail', slug=blog.slug)

codes/blog/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block title %} My Blog Listing Page {% endblock %}

{% block body %}
<h1 class="text-center mb-5">My Blog</h1>
{% if blogs %}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Activity</th>
        </tr>
    </thead>
    <tbody>
        {% for blog in blogs %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
                <a href="{{blog.get_panel_detail_blog_url}}">{{blog.title}}</a>
            </td>
            <td>
                <a href="{% url 'panel:delete_blog' blog.id %}" class="btn btn-danger">Remove</a>
                <a href="{% url 'panel:update_blog' blog.id %}" class="btn btn-info">Update</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include 'include/blog_paginator.html' %}
{% else %}
<p class="alert alert-danger">you have no blog. for create blog use this <a href="{% url 'panel:create_blog' %}">link</a></p>
{% endif %}
{% endblock %}

codes/blog/templates/blog/create_blog.html
{% extends 'base.html' %}

{% block title %} Create Blog Page {% endblock %}

{% block body %}

<div class="mx-auto card mx-auto" style="padding: 0px;">
    <div class="card-header">Create Blog</div>
    <form class="card-body needs-validation d-flex flex-wrap justify-content-center" action="" method="post" enctype="multipart/form-data">
        {% for field in form %}
            <div class="fieldWrapper col-md-12">
                <div class="label_and_error">
                    <div class="label_form_side">
                        {{ field.label_tag }}
                    </div>
                    {{ field.errors }}
                </div>
                <div>{{ field }}</div>  
            </div>
        {% endfor %}
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            <input type="submit" value="Create" class="btn btn-primary mt-3">
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}

codes/blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %} detail page| {{blog.title}}{% endblock %}
{% block header %}{{ form.media }}{% endblock %}

{% block body %}
<h1>Detail blog post page</h1>
<div class="row tm-row">
    <div class="col-12">
        <hr class="tm-hr-primary tm-mb-55">
        <!-- Video player 1422x800 -->
        <img style="width: 100%;" src="{{blog.baner.url}}" controls class="tm-mb-40">
    </div>
</div>
<div class="row tm-row">
    <div class="col-lg-8 tm-post-col">
        <div class="tm-post-full">
            <div class="mb-4">
                <div class="d-flex justify-content-between align-items-center flex-wrap">
                    <h2 class="pt-2 tm-color-primary tm-post-title">{{blog.title}}</h2>

                    <div class="d-flex justify-content-between align-items-center flex-wrap ">
                        <a href="{% url 'blog:favorite' blog.id %}">
                            <svg class="favorite" xmlns="http://www.w3.org/2000/svg"
                                fill="{% if can_add_to_favorite %}none{% else %}currentColor{% endif %}"
                                viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z" />
                            </svg>
                        </a>
                        <div>
                            <a class="like" href="{% url 'blog:like' blog.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                    fill="{% if can_like %}none{% else %}currentColor{% endif %}" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
                                </svg>
                            </a>
                            <span class="like">{{blog.like_count}}</span>
                        </div>
                    </div>
                </div>
                <p class="tm-mb-40">creaed at: {{blog.created|date:'Y/m/d'}}<br>
                    last time updated: {{blog.updated|date:'Y/m/d'}}<br>
                    posted by {{blog.author.profile.user_info}}
                </p>
                <p>{{blog.text|safe}}</p>
                <span>Category: </span>
                <span class="tm-color-primary">
                    {% for cat in blog.cates.all %}
                    <span class="category category-detail tm-color-primary">{{cat.title}}</span>
                    {% endfor %}
                </span>
            </div>

            <!-- Comments -->
            <div>
                <h2 class="tm-color-primary tm-post-title">Comments</h2>
                <hr class="tm-hr-primary tm-mb-45">
                {% for comment in comments %}
                <div class="tm-comment tm-mb-45">
                    <figure class="tm-comment-figure">
                        <img src="{{comment.user.profile.profile.url}}" alt="Image"
                            class="mb-2 rounded-circle img-thumbnail">
                        <figcaption class="tm-color-primary text-center">{{comment.user.profile.user_info}}</figcaption>
                    </figure>
                    <div>
                        <p>{{comment.text|safe}}</p>
                        <div class="d-flex justify-content-between">
                            <!-- <a href="#" class="tm-color-primary">REPLY</a> -->
                            <span class="tm-color-primary">{{blog.created|date:'Y/m/d'}}</span>
                        </div>
                    </div>
                </div>
                {% for reply in comment.reply_comments %}
                <div class="tm-comment-reply tm-mb-45">
                    <div class="tm-comment">
                        <figure class="tm-comment-figure">
                            <img src="{{reply.user.profile.profile.url}}" alt="Image"
                                class="mb-2 rounded-circle img-thumbnail">
                            <figcaption class="tm-color-primary text-center">{{reply.user.profile.user_info}}
                            </figcaption>
                        </figure>
                        <p>{{reply.text|safe}}</p>
                    </div>
                    <span class="d-block text-right tm-color-primary">{{reply.created|date:'Y/m/d'}}</span>
                </div>
                {% endfor %}
                <hr>
                {% empty %}
                <p class="alert alert-danger">no comment found</p>
                {% endfor %}
                {% if request.user.is_authenticated %}
                <form action="{% url 'blog:create_comment' blog.id %}" method="post"
                    class="tm-color-secondary mb-5 ">
                    {% csrf_token %}
                    {{form}}
                    <input type="submit" value="send" class="btn btn-primary tm-btn-small mt-2">
                </form>
                {% else %}
                <div class="alert alert-danger">for send comment. you should login first</div>
                {% endif %}
            </div>
        </div>
    </div>
    <aside class="col-lg-4 tm-aside-col">
        <div class="tm-post-sidebar">
            <hr class="mb-3 tm-hr-primary">
            <h2 class="mb-4 tm-post-title tm-color-primary">Categories</h2>
            <ul class="tm-mb-75 pl-5 tm-category-list">
                {% for cat in categories %}
                <li><a href="{% url 'blog:blog_all' %}?category={{cat.slug}}" class="tm-color-primary">{{cat.title}}</a>
                </li>
                {% endfor %}
            </ul>
            <hr class="mb-3 tm-hr-primary">
            <h2 class="tm-mb-40 tm-post-title tm-color-primary">Related Posts</h2>
            {% for related in blog.related_blog %}
            <a href="{{related.get_absolute_url}}" class="d-block tm-mb-40">
                <figure>
                    <img src="{{related.baner.url}}" alt="Image" class="mb-3 img-fluid">
                    <figcaption class="tm-color-primary">{{related.title}}</figcaption>
                </figure>
            </a>
            {% empty %}
            <p class="alert alert-danger">can not find related blog</p>
            {% endfor %}
        </div>
    </aside>
</div>

{% endblock %}

codes/blog/templates/blog/detail_blog.html
{% extends 'base.html' %}

{% block title %} Detail Blog Page | {blog.title} {% endblock %}

{% block body %}
<h1>Detail blog post page</h1>
<div class="row tm-row">
    <div class="col-12">
        <hr class="tm-hr-primary tm-mb-55">
        <img style="width: 100%;" src="{{blog.baner.url}}" controls class="tm-mb-40">
    </div>
</div>
<div class="row tm-row">
    <div class="col-lg-8 tm-post-col">
        <div class="tm-post-full">
            <div class="mb-4">
                <div class="d-flex justify-content-between align-items-center flex-wrap">
                    <h2 class="pt-2 tm-color-primary tm-post-title">{{blog.title}}</h2>
                </div>
                <p class="tm-mb-40">creaed at: {{blog.created|date:'Y/m/d'}}<br>
                    last time updated: {{blog.updated|date:'Y/m/d'}}<br>
                    posted by {{blog.author.profile.user_info}}
                </p>
                <p>{{blog.text|safe}}</p>
                <span>Category: </span>
                <span class="tm-color-primary">
                    {% for cat in blog.cates.all %}
                    <span class="category category-detail tm-color-primary">{{cat.title}}</span>
                    {% endfor %}
                </span>
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-between align-items-center my-5">
    <div>
        <a href="{% url 'panel:delete_blog' blog.id %}" class="btn btn-danger">Delete</a>
    </div>
    <div>
        <a href="{% url 'panel:update_blog' blog.id %}" class="btn btn-info">Update</a>
        <a href="{% url 'panel:my_blog' %}" class="btn btn-info">My blog</a>
        <a href="{% url 'blog:detail' blog.slug %}" class="btn btn-info">View in site</a>
    </div>
</div>
{% endblock %}

codes/blog/templates/blog/listing_favorite.html
{% extends 'base.html' %}

{% block title %} Favorite Blog Page {% endblock %}

{% block body %}
<h1 class="text-center mb-5">My Favorite Blog</h1>
{% if favorites %}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Activity</th>
        </tr>
    </thead>
    <tbody>
        {% for favorite in favorites %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
                <a href="{{ favorite.blog.get_absolute_url }}">{{favorite.blog}}</a>
            </td>
            <td>
                <a href="{% url 'blog:favorite' favorite.blog.id %}" class="btn btn-danger">Remove</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="alert alert-danger">you have no favorite.</p>
{% endif %}
{% endblock %}

codes/blog/templates/blog/show_all.html
{% extends 'base.html' %}
{% load static %}
{% block title %}show all blog{% endblock %}

{% block body %}
<div class="row tm-row">
    <div class="col-4 filter">
        {% if search %}<p>search text: {{search}}</p>{% endif %}
        {% if category %}<p>your category: {{category}}</p>{% endif %}
        <p>result found: {{result_count}}</p>
    </div>            
    <div class="col-8">
        <form method="GET" action="" class="form-inline tm-mb-80 tm-search-form">                
            <input class="form-control tm-search-input" name="q" type="text" {% if search %}value="{{search}}" {% endif %} placeholder="Search..." aria-label="Search">
            <button class="tm-search-button" type="submit">
                <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
            </button>
            <a href="{% url 'blog:blog_all' %}">remove search</a>                         
        </form>
    </div>
</div>            
<div class="row tm-row">
    {% for blog in blogs %}
    <article class="col-12 col-md-6 tm-post">
        <hr class="tm-hr-primary">
        <a href="{{blog.get_absolute_url}}" class="effect-lily tm-post-link tm-pt-60">
            <div class="tm-post-link-inner">
                <img src="{{blog.baner.url}}" alt="Image" class="img-fluid">                            
            </div>
            <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{blog.title}}</h2>
        </a>                    
        <div class="d-flex justify-content-between align-items-center tm-pt-45">
            <div class="category-container">
                {% for cat in blog.cates.all %}
                <span class="tm-color-primary category">{{cat.title}}</span>
                {% endfor %}
            </div>
            <span class="tm-color-primary">{{blog.updated|date:'Y/m/d'}}</span>
        </div>
        <hr>
        <div class="d-flex justify-content-between">
            <div class="parent-info">
                <div class="info">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 0 1 .865-.501 48.172 48.172 0 0 0 3.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0 0 12 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018Z" />
                    </svg>
                    <span>{{blog.comments_count}}</span>
                </div>
                <div class="info">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
                    </svg>
                    <span>{{blog.like_count}}</span>   
                </div>    
            </div>       
            <span>author: {{blog.author.profile.user_info}}</span>
        </div>
    </article>
    {% empty %}
    <p class="alert alert-danger col-12">there is no result found</p>
    {% endfor %}
</div>
{% include 'include/blog_paginator.html' %}
{% endblock %}

codes/blog/templates/blog/update_blog.html
{% extends 'base.html' %}

{% block title %} Update Blog Page {% endblock %}
{% block header %}{{ form.media }}{% endblock %}

{% block body %}

{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endfor %}
{% endif %}
<div class="mx-auto card mx-auto" style="padding: 0px;">
    <div class="card-header">Update Blog</div>
    <form novalidate class="card-body needs-validation d-flex flex-wrap justify-content-center" action="" method="post" enctype="multipart/form-data">
        {% if form.instance.baner %}
        <div class="image-container mx-auto" style="width: 100%;">
            <img style="margin: 0px auto;" src="{{ form.instance.baner.url }}" alt="baner Picture">
        </div>
        {% endif %}
        {% for field in form %}
            <div class="fieldWrapper col-md-12">
                <div class="label_and_error">
                    <div class="label_form_side">
                        {{ field.label_tag }}
                    </div>
                    {{ field.errors }}
                </div>
                <div>{{ field }}</div>  
            </div>
        {% endfor %}
        {% csrf_token %}
        <div class="d-flex justify-content-between align-items-center mt-3 mx-auto" style="width: 75%;">
            <input type="submit" value="Update" class="btn btn-primary">
            <a href="{% url 'panel:detail_blog' form.instance.id %}" class="btn btn-primary">View</a>
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}